// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: steammessages.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_steammessages_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60000,
		Name:          "key_field",
		Tag:           "varint,60000,opt,name=key_field,def=0",
		Filename:      "steammessages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         60000,
		Name:          "msgpool_soft_limit",
		Tag:           "varint,60000,opt,name=msgpool_soft_limit,def=32",
		Filename:      "steammessages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         60001,
		Name:          "msgpool_hard_limit",
		Tag:           "varint,60001,opt,name=msgpool_hard_limit,def=384",
		Filename:      "steammessages.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool key_field = 60000;
	E_KeyField = &file_steammessages_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional int32 msgpool_soft_limit = 60000;
	E_MsgpoolSoftLimit = &file_steammessages_proto_extTypes[1]
	// optional int32 msgpool_hard_limit = 60001;
	E_MsgpoolHardLimit = &file_steammessages_proto_extTypes[2]
)

var File_steammessages_proto protoreflect.FileDescriptor

const file_steammessages_proto_rawDesc = "" +
	"\n" +
	"\x13steammessages.proto\x1a google/protobuf/descriptor.proto:C\n" +
	"\tkey_field\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xd4\x03 \x01(\b:\x05falseR\bkeyField:S\n" +
	"\x12msgpool_soft_limit\x12\x1f.google.protobuf.MessageOptions\x18\xe0\xd4\x03 \x01(\x05:\x0232R\x10msgpoolSoftLimit:T\n" +
	"\x12msgpool_hard_limit\x12\x1f.google.protobuf.MessageOptions\x18\xe1\xd4\x03 \x01(\x05:\x03384R\x10msgpoolHardLimitB\x05H\x01\x80\x01\x00"

var file_steammessages_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),   // 0: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_steammessages_proto_depIdxs = []int32{
	0, // 0: key_field:extendee -> google.protobuf.FieldOptions
	1, // 1: msgpool_soft_limit:extendee -> google.protobuf.MessageOptions
	1, // 2: msgpool_hard_limit:extendee -> google.protobuf.MessageOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steammessages_proto_init() }
func file_steammessages_proto_init() {
	if File_steammessages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_proto_rawDesc), len(file_steammessages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_proto_goTypes,
		DependencyIndexes: file_steammessages_proto_depIdxs,
		ExtensionInfos:    file_steammessages_proto_extTypes,
	}.Build()
	File_steammessages_proto = out.File
	file_steammessages_proto_goTypes = nil
	file_steammessages_proto_depIdxs = nil
}
