version: 2
run:
  allow-parallel-runners: true

exclusions:
  paths:
    - parser_interface.go
    - '*\\.pb\\.go$'
    - parser_interface.go

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gocognit
    - godox
    - nestif
    - prealloc
    - revive
